[package]
name = "rust_image_canvas"
version = "0.1.0"
edition = "2021"


[dependencies]
eframe = "0.24"
image = "0.24"
rfd = "0.14" 
winapi = { version = "0.3", features = ["winuser"] }
imageproc = "0.23"

